---
galaxy_info:
  role_name: suricata
  author: Brad Dabbs
  description: Deploys Suricata as a component of RockNSM
  company: RockNSM Foundation

  license: Apache-2.0
  min_ansible_version: 2.7

  platforms:
    - name: RedHat
      versions:
        - 7
    - name: CentOS
      versions:
        - 7
dependencies:
  - name: Install and configure filebeat
    role: filebeat
    vars:
      filebeat_configs:
        - { src: 'fb-suricata.yml.j2', dest: 'suricata.yml' }
